CC		 = armv5te-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -L. -static

OBJ			= bin/armv5el
EXECUTABLE	= bin/shairport_helper-armv5el

include Makefile

