CC	 	= aarch64-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -L. -static

OBJ			= bin/aarch64
EXECUTABLE	= bin/shairport_helper-aarch64

include Makefile

