CFLAGS  ?= -Wall -fPIC -ggdb -m64 -O2 $(OPTS) -I/usr/include/i386-linux-gnu $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -m64 -lpthread -lcrypto -ldl -lm -lrt -L. -static

OBJ			= bin/x86-64
EXECUTABLE 	= bin/shairport_helper-x64-linux

include Makefile

