CC=armv6j-cross-linux-gnueabihf-gcc
CFLAGS  ?= -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -L. -static

OBJ			= bin/armv6hf
EXECUTABLE	= bin/shairport_helper-armv6hf

include Makefile

