CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -lpthread -lcrypto -ldl -lm -lrt -lz -L. -static

OBJ			= bin/x86-64
EXECUTABLE 	= bin/shairport_helper-x64-linux

include Makefile

